server:
  port: 8001
  # 添加Jetty服务器配置（可选）
  jetty:
    threads:
      max: 200
      min: 10

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 8.x驱动
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      test-on-borrow: true

# MyBatis简化配置（推荐）
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.example.springcloudapi.pojo
  configuration:
    map-underscore-to-camel-case: true  # 自动驼峰转换
    cache-enabled: false